"""create_table_user_outbound

Revision ID: b97236b272bf
Revises: 
Create Date: 2025-01-24 12:30:47.341059+09:00

"""
from alembic import op
import sqlalchemy as sa
from app.migrations.for_each_schema import for_each_schema

# revision identifiers, used by Alembic.
revision = 'b97236b272bf'
down_revision = None
branch_labels = None
depends_on = None


@for_each_schema
def upgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_outbound',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary Key'),
                    sa.Column('user_id', sa.Integer(), nullable=False, comment='user_id of inbound'),
                    sa.Column('outbound_user_id', sa.Integer(), nullable=True,
                              comment='user_id from old Evercall operator'),
                    sa.Column('extension_id', sa.Integer(), nullable=False, comment='Extension ID'),
                    sa.Column('delete_flg', sa.Boolean(), nullable=False,
                              comment='Delete flag (0: active, 1: deleted)'),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users_outbound')),
                    schema=schema
                    )
    # ### end Alembic commands ###


@for_each_schema
def downgrade(schema: str) -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_outbound', schema=schema)
    # ### end Alembic commands ###


def has_table(engine, table_name: str, schema: str) -> bool:
    """テーブルが存在するかチェックする."""
    inspected = sa.inspect(engine)
    has = inspected.has_table(table_name, schema)
    return has


def has_index(engine, table_name: str, index_name: str, schema: str) -> bool:
    """インデックスが存在するかチェックする."""
    inspected = sa.inspect(engine)
    indexes = inspected.get_indexes(table_name, schema)
    has: bool = False
    for idx in indexes:
        if idx["name"] == index_name:
            has = True
            break
    return has


def has_column(engine, table_name: str, column_name: str, schema: str) -> bool:
    """カラムが存在するかチェックする."""
    inspected = sa.inspect(engine)
    columns = inspected.get_columns(table_name, schema)
    has: bool = False
    for c in columns:
        if c["name"] == column_name:
            has = True
            break
    return has
